/*
    STEP 1: Set the context
*/
USE ROLE SYSADMIN;
USE WAREHOUSE LOAD_WH;

/*
    STEP 2: Create database, schema, stage, and file formats
*/
CREATE DATABASE IF NOT EXISTS HEALTHCARE_DEMO;
USE DATABASE HEALTHCARE_DEMO;
CREATE SCHEMA IF NOT EXISTS CLINICAL_TRIAL;
USE SCHEMA CLINICAL_TRIAL;

CREATE STAGE IF NOT EXISTS VHOL_S3_STAGE URL='s3://snowflake-corp-se-workshop/VHOL_Snowflake_Tableau_Healthcare/';
LS @VHOL_S3_STAGE;

CREATE FILE FORMAT IF NOT EXISTS CSV_FMT 
    TYPE = 'CSV' 
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';
    
CREATE FILE FORMAT IF NOT EXISTS JSON_FMT 
    TYPE = 'JSON';

/*
    STEP 3: Create tables for sample datasets
*/
CREATE TABLE IF NOT EXISTS FACILITIES (
	ID NUMBER(38,0),
	NCT_ID VARCHAR(15),
	STATUS VARCHAR(25),
	NAME VARCHAR(255),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	ZIP VARCHAR(50),
	COUNTRY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PATIENT (
	PATIENT_ID VARCHAR(16777216),
	ID NUMBER(38,0),
	NAME VARCHAR(50),
	GENDER VARCHAR(6),
	DATE_OF_BIRTH DATE
);

CREATE TABLE IF NOT EXISTS PATIENT_BODYTEMP_HEALTH_DATA (
	MEASUREDATE DATE,
	PATIENTNR VARCHAR(10),
	MEASUREVALUEC NUMBER(3,1),
	MEASUREVALUEF NUMBER(5,1),
	PATIENTAGE NUMBER(38,0),
	FACILITY_ID NUMBER(38,0),
	NCT_ID VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS US_ZIPCODES (
	ZIP_CODE VARCHAR(5),
	TYPE VARCHAR(25),
	CITY VARCHAR(100),
	ACCEPTABLE_CITIES VARCHAR(500),
	STATE_CODE VARCHAR(2),
	COUNTY_NAME VARCHAR(60),
	TIMEZONE VARCHAR(60),
	COUNTRY_CODE VARCHAR(2),
	LAT FLOAT,
	LONG FLOAT,
	GEOCODE GEOGRAPHY,
	FIPS VARCHAR(5),
	ORG_COUNTY_NAME VARCHAR(60)
);

/*
    STEP 4: Load files into tables
*/
USE WAREHOUSE LOAD_WH;

COPY INTO FACILITIES FROM @VHOL_S3_STAGE/facilities.csv.gz file_format=(format_name='CSV_FMT');
COPY INTO PATIENT FROM @VHOL_S3_STAGE/patient.csv.gz file_format=(format_name='CSV_FMT');
COPY INTO US_ZIPCODES FROM @VHOL_S3_STAGE/us_zipcodes.csv.gz file_format=(format_name='CSV_FMT');

select $1 from @VHOL_S3_STAGE/patient_bodytemp.json.gz (file_format => 'JSON_FMT');

/*
  *** THIS IS AN ALTERNATE APPROACH, PLEASE DO NOT RUN ***

  CREATE TABLE PBHD(
      V   VARIANT
  );

  COPY INTO PBHD FROM @VHOL_S3_STAGE/patient_bodytemp.json.gz file_format=(format_name='JSON_FMT');

  SELECT * FROM PBHD LIMIT 10;
  
  CREATE VIEW...
*/

COPY INTO PATIENT_BODYTEMP_HEALTH_DATA FROM (
  SELECT 
    $1:MEASUREDATE::DATE
    ,$1:PATIENTNR::STRING
    ,$1:MEASUREVALUEC::NUMBER
    ,$1:MEASUREVALUEF::NUMBER
    ,$1:PATIENTAGE::NUMBER
    ,$1:FACILITY_ID::NUMBER
    ,$1:NCT_ID::string
  FROM @VHOL_S3_STAGE/patient_bodytemp.json.gz
  )
file_format=(format_name='JSON_FMT');


--------------------------------   STOP! --------------------------------

/*
    STEP 5: Bring in Starschema data from the Data Marketplace
    1) Switch role to ACCOUNTADMIN, or a role granted the IMPORT SHARE privilege
    2) Click on Data Marketplace
    3) Log in to the new UI
    4) Search for "Starschema", select the COVID-19 dataset
    5) Get the data, grant to SYSADMIN, accept terms
    6) Return to original browser tab, come back to this Worksheet
*/

SELECT * 
  FROM "STARSCHEMA_COVID19"."PUBLIC"."NYT_US_COVID19" 
 ORDER BY DATE DESC
 LIMIT 10;

/*
    STEP 6: Create views, and a secure view

    Here is a regular view, but this is just for demonstration purposes:
    CREATE OR REPLACE VIEW PATIENT_BODYTEMP_DATA_VW
    AS
    SELECT
        PT.PATIENTNR
        ,PT.MEASUREDATE
        ,PT.MEASUREVALUEC
        ,PT.MEASUREVALUEF
        ,PT.FACILITY_ID
        ,PT.NCT_ID
        ,P.DATE_OF_BIRTH
        -- ,P.NAME
    FROM PATIENT_BODYTEMP_HEALTH_DATA  PT
      JOIN PATIENT P 
        ON P.ID = PT.PATIENTNR;

    SELECT * FROM PATIENT_BODYTEMP_DATA_VW;
    DROP VIEW PATIENT_BODYTEMP_DATA_VW;
*/

CREATE OR REPLACE SECURE VIEW PATIENT_BODYTEMP_DATA_SV
AS
SELECT
    PT.PATIENTNR
    ,PT.MEASUREDATE
    ,PT.MEASUREVALUEC
    ,PT.MEASUREVALUEF
    ,PT.FACILITY_ID
    ,PT.NCT_ID
    ,P.DATE_OF_BIRTH
    -- ,P.NAME
FROM PATIENT_BODYTEMP_HEALTH_DATA  PT
  JOIN PATIENT P 
    ON P.ID = PT.PATIENTNR;
    
-- SELECT * FROM PATIENT_BODYTEMP_DATA_SV LIMIT 10;

CREATE OR REPLACE VIEW US_FACILITIES_VW
AS
SELECT 
    F.ID
    ,F.NCT_ID
    ,F.STATUS
    ,F.NAME
    ,F.CITY
    ,F.STATE
    ,F.ZIP
    ,F.COUNTRY
    ,Z.LAT   AS LATITUDE
    ,Z.LONG  AS LONGITUDE
    ,Z.GEOCODE 
    ,Z.COUNTY_NAME
    ,Z.FIPS
FROM FACILITIES F
  JOIN US_ZIPCODES Z
    ON F.ZIP = Z.ZIP_CODE 
WHERE F.COUNTRY = 'United States';

CREATE OR REPLACE VIEW PATIENT_FACILITIES_COVID19_VW
AS
SELECT 
    PBD.MEASUREDATE
    ,PBD.PATIENTNR
    ,PBD.MEASUREVALUEC TEMPC
    ,PBD.MEASUREVALUEF TEMPF
    ,PBD.DATE_OF_BIRTH
    ,DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) AGE
    ,F.ID FACILITY_ID
    ,F.NCT_ID
    ,F.STATUS FACILITY_STATUS
    ,F.NAME  FACILITY_NAME
    ,F.CITY
    ,F.STATE
    ,F.ZIP
    ,F.COUNTRY
    ,F.LATITUDE
    ,F.LONGITUDE
    ,F.COUNTY_NAME COUNTY
    ,COV.DATE
    ,COV.FIPS
    ,COV.CASES_SINCE_PREV_DAY
    ,COV.DEATHS_SINCE_PREV_DAY
FROM PATIENT_BODYTEMP_DATA_SV PBD
  JOIN US_FACILITIES_VW F
    ON PBD.FACILITY_ID = F.ID
   AND PBD.NCT_ID = F.NCT_ID
  JOIN "STARSCHEMA_COVID19"."PUBLIC"."NYT_US_COVID19" COV
    ON COV.FIPS = F.FIPS
   AND COV.DATE = PBD.MEASUREDATE;

-- Find average body temp and age in counties with the most COVID cases
SELECT 
    AVG(TEMPF) AVG_BODYTEMP
    ,AVG(
        DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE())
     ) AVG_AGE
    ,COUNTY
    ,STATE
    ,SUM(CASES_SINCE_PREV_DAY) TOTAL_CASES
 FROM PATIENT_FACILITIES_COVID19_VW
GROUP BY COUNTY, STATE
ORDER BY 1 DESC;

/*
    Cleanup (optional)
    Execute these commands after you've completed the lab
*/
USE ROLE ACCOUNTADMIN;
DROP DATABASE "STARSCHEMA_COVID19";
DROP DATABASE "HEALTHCARE_DEMO";
DROP WAREHOUSE TABLEAU_WH;
DROP WAREHOUSE LOAD_WH;